name: "Tests"
on: [push]
jobs:
  Running-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "🧪 Running tests 🧪"
        uses: actions/checkout@v2
      - name: "✨ Installing dependencies ✨"
        run: npm ci
      - name: "👨‍💻 Running tests 👨‍💻"
        run: npm test
